Repository niteshjitender/HacktoberFest2022, pull requests merged in 2022-10, with the labels that each got.

#2 New user sayam
  Contributors.md
  MyFirstContribution/script.js
  MyFirstContribution/userImageData/sayamalvi.jpeg
Labels: hacktoberfest-accepted

#7 Add Aditya Saini to Contributors list
  Contributors.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 add my profile
  Contributors.md
Labels: hacktoberfest-accepted, PR-accepted

#13 updated contributers
  Contributors.md
Labels: hacktoberfest-accepted, PR-accepted

#16 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#20 added my contribution
  Contributors.md
  MyFirstContribution/script.js
  MyFirstContribution/userImageData/sainathd07.jpg
Labels: hacktoberfest-accepted, PR-accepted

#22 Added Contributors section in readme file
  README.md
Labels: hacktoberfest-accepted, PR-accepted
